apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.6.1
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: longhorn
  targetNamespace: longhorn-system
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      reclaimPolicy: Delete
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: false
