apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - cert-manager
  - external-dns
  - longhorn
  - metallb
  - metrics-server
  - kube-prometheus-stack
  - loki-stack
  - weave-gitops
