apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.14.4
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: external-dns
  targetNamespace: external-dns
  upgrade:
    remediation:
      retries: 3
  values:
    provider:
      name: cloudflare
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: apiKey
          name: cloudflare-api-key
    policy: sync
    txtOwnerId: homelab
