apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 10.0.0
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: loki-stack
  targetNamespace: monitoring
  timeout: 10m
  upgrade:
    remediation:
      retries: 3
  values:
    loki:
      persistence:
        enabled: true
        size: 20Gi
        storageClassName: longhorn
      serviceMonitor:
        enabled: true
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
