apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 5.43.2
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: -1
  releaseName: loki
  targetNamespace: monitoring
  timeout: 10m
  upgrade:
    remediation:
      retries: 3
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      image:
        tag: 3.5.5
      limits_config:
        allow_structured_metadata: false
      persistence:
        enabled: true
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      serviceMonitor:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3100"
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: true
      dashboards:
        enabled: true
      rules:
        enabled: true
    gateway:
      enabled: false
