apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 5.43.2
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: -1
  releaseName: loki
  targetNamespace: monitoring
  timeout: 10m
  upgrade:
    remediation:
      retries: 3
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      image:
        tag: 3.5.5
      config: |
        {}
      structuredConfig:
        auth_enabled: false
        server:
          http_listen_port: 3100
          grpc_listen_port: 9095
        common:
          path_prefix: /var/loki
          replication_factor: 1
          compactor_address: loki
          storage:
            filesystem:
              directory: /var/loki/tsdb-object-store
        memberlist:
          join_members:
            - loki-memberlist
        runtime_config:
          file: /etc/loki/runtime-config/runtime-config.yaml
        schema_config:
          configs:
            - from: "2022-01-11"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        storage_config:
          filesystem:
            directory: /var/loki/tsdb-object-store
          tsdb_shipper:
            active_index_directory: /var/loki/tsdb-index
            cache_location: /var/loki/tsdb-cache
        compactor:
          working_directory: /var/loki/compactor
        limits_config:
          allow_structured_metadata: true
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
        ruler:
          storage:
            type: local
            local:
              directory: /var/loki/rules
        query_range:
          align_queries_with_step: true
        frontend:
          scheduler_address: ""
        frontend_worker:
          scheduler_address: ""
        index_gateway:
          mode: ring
        tracing:
          enabled: false
      persistence:
        enabled: true
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      serviceMonitor:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3100"
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: true
      dashboards:
        enabled: true
      rules:
        enabled: true
    gateway:
      enabled: false
