apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.15.5
  dependsOn:
    - name: loki
      namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: -1
  releaseName: promtail
  targetNamespace: monitoring
  timeout: 10m
  upgrade:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
    config:
      clients:
        - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      snippets:
        pipelineStages: []
