apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-logs-pv
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: loki-local
  local:
    path: /var/lib/homelab-storage/logs/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-node-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-logs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: loki-local
  volumeName: loki-logs-pv
  resources:
    requests:
      storage: 400Gi
