apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/homelab/infrastructure/crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 5m
  wait: true
