apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sources
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-crds
  interval: 10m
  path: ./clusters/homelab/infrastructure/sources/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 5m
  wait: true
