apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - infrastructure-crds.yaml
  - infrastructure-sources.yaml
  - infrastructure-addons.yaml
  - apps.yaml
