apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - infrastructure-crds.yaml
  - infrastructure-sources.yaml
  - infrastructure-addons.yaml
  - apps.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: source-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=OCIRepositories=true
