apiVersion: v1
kind: Secret
metadata:
  name: cluster-user-auth
  namespace: weave-gitops
  annotations:
    kubernetes.io/service-account.name: weave-gitops-user
type: kubernetes.io/service-account-token
