apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      version: 4.0.35
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: weave-gitops
  targetNamespace: weave-gitops
  upgrade:
    remediation:
      retries: 3
  values:
    adminUser:
      create: false
      existingSecret: weave-gitops-admin
    clusterUser:
      serviceAccount:
        create: false
        name: weave-gitops-user
      authSecret:
        create: false
        name: cluster-user-auth
    service:
      type: ClusterIP
