apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      version: 4.0.35
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: weave-gitops
  targetNamespace: weave-gitops
  upgrade:
    remediation:
      retries: 3
  values:
    WEAVE_GITOPS_FEATURE_TELEMETRY: "true"
    adminUser:
      create: true
      username: admin
      passwordHash: "$2y$05$E7PO0lrzjRrWK9lMCAjc4evB3AnGgGebcur.lHl402i0SLujwDNJW"
    service:
      type: ClusterIP
