apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.18.2
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: cert-manager
  targetNamespace: cert-manager
  upgrade:
    remediation:
      retries: 3
  values:
    installCRDs: true
