apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: 0.15.2
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: metallb
  targetNamespace: metallb-system
  upgrade:
    remediation:
      retries: 3
  values: {}
