apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.15.5
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: cilium
  targetNamespace: kube-system
  upgrade:
    remediation:
      retries: 3
  values:
    kubeProxyReplacement: false
    k8sServiceHost: 192.168.0.100
    k8sServicePort: 6443
