apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  chart:
    spec:
      chart: local-path-provisioner
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
      version: 0.0.26
  install:
    remediation:
      retries: -1
  interval: 30m
  releaseName: local-path-provisioner
  targetNamespace: local-path-storage
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: v0.0.26
    storageClass:
      defaultClass: false
      name: local-path
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /opt/local-path-provisioner
